# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59f89217e5bd030bbbdb5dd09eb6c1f9dc0cb1f16fd1825638f2ac5adcc8b085cf5d801640c3b18fb63859bf14d128b08cd33b59fce39a709478881b006cd49e

test:
  secret_key_base: 68eaadd757509e0514dac708f88d73b5c46f33ebec6eca9728640783cb69e06c79322025165abdb8cfa2971fe3e6fbe59715a61f6f9d76ca5c9833af472307d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
